collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
      image: /icons/favicon-maxres.png
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      image: /icons/favicon-maxres.png
  - scope:
      path: ""
    values:
      layout: "default"
      image: /icons/favicon-maxres.png

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: pencilvoid.neocities.org
tagline: The Pencilzone
url: https://pencilvoid.neocities.org
twitter:
  username: pencilvoid
locale: en_GB

feed:
  posts_limit: 512

source: "./site"