defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: sieveplate/:categories/:year/:month/:title/
  - scope:
      path: "/games/c2"
    values:
      layout: "default_c2game"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-datapage-generator

title: pencilvoid.neocities.org
tagline: The Pencilzone
url: https://pencilvoid.neocities.org
twitter:
  username: pencilvoid
  card: summary
locale: en_GB

source: "./site"

page_gen-dirs: true

page_gen:
- data: authors
  template: author
  dir: /authors
  name: id
  title: fullname