defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: sieveplate/:categories/:year/:month/:title/
  - scope:
      path: "/games/c2"
    values:
      layout: "default_c2game"
  - scope:
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
    values:
      layout: "default"


plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at
  - jekyll-datapage-generator

title: pencilvoid.neocities.org
tagline: The Pencilzone
url: https://pencilvoid.neocities.org
twitter:
  username: pencilvoid
  card: summary
locale: en_GB
author: xpv

source: "./site"

collections:
  authors:
    output: true
    permalink: /:collection/:name/

page_gen-dirs: true

page_gen:
- data: gallery_items
  template: gallery_item
  dir: /art
  name: id
  title: name
