defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
      permalink: sieveplate/:categories/:year/:month/:title/
  - scope:
      path: "/games/c2"
    values:
      layout: "default_c2game"
  - scope:
      type: "authors"
    values:
      layout: "author"
  - scope:
      type: "gallery_items"
    values:
      layout: "gallery_item"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-last-modified-at

title: pencilvoid.neocities.org
tagline: The Pencilzone
url: https://pencilvoid.neocities.org
twitter:
  username: pencilvoid
  card: summary
locale: en_GB
author: pencilvoid

source: "./source"
destination: "./build"
exclude:
  - /*.pdn

collections:
  authors:
    output: true
    permalink: /:collection/:name/
  gallery_items:
    output: true
    permalink: /photosystems/:title/
