collections:
  authors:
    output: true

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

title: pencilvoid.neocities.org
tagline: The Pencilzone
url: https://pencilvoid.neocities.org
logo: /icons/favicon-128x.png
twitter:
  username: pencilvoid
  card: summary
locale: en_GB

feed:
  path: /sieveplate/feed.xml
  posts_limit: 512
  excerpt_only: false

source: "./site"
